version: '3.8'

volumes:
  php-fpm-socket:

services:
  db:
    image: postgres:13.5-alpine
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'

  web:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - php-fpm-socket:/var/run
      - ./backend/src/:/var/www/html/
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - php-fpm-socket:/var/run
      - ./backend/src/:/var/www/html/
    depends_on:
      - db
    tty: true
    stdin_open: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: /bin/sh -c 'yarn && yarn dev'
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    environment: 
      - NODE_ENV=development
    tty: true
