version: '3'

services:
  db:
    image: postgres:13.3
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: new_db
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'
      TZ: Asia/Tokyo
  
  # backend:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/code
    ports:
      - 8000:8000
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  
  # frontend:
  front:
    build: 
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/app
    ports:
      - 3000:3000
    environment: 
      - NODE_ENV=development
    command: /bin/sh -c 'cd react_app && yarn start'
