version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./api/tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
  front:
    build: 
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/app
    command: /bin/sh -c "cd react_app && yarn start"
    ports:
      - '8000:3000'
