version: '3'
services:
  node:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    command: sh -c "cd react_sample && yarn start"
    ports:
      - "8000:3000"
