version: "3"
services:
  app:
    build: 
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./log:/var/log
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_NAME:-laravel_local}
      - DB_USERNAME=${DB_USER:-admin}
      - DB_PASSWORD=${DB_PASS:-admin}

  web:
    image: nginx:latest
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: postgres:13
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=${DB_NAME:-laravel_local}
      - POSTGRES_USER=${DB_USER:-admin}
      - POSTGRES_PASSWORD=${DB_PASS:-admin}
      - TZ=${TZ:-Asia/Tokyo}

  pgadmin4:
    image: dpage/pgadmin4:5.0
    ports:
      - 8580:80
    volumes:
      - ./docker/pgadmin4:/var/lib/pgadmin
    links:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin

  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - 1080:1080
