version: '3.8'

volumes:
  php-fpm-socket:

services:
  db:
    image: postgres:13.5-alpine
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'

  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    command: /bin/sh
    volumes:
      - php-fpm-socket:/var/run/php-fpm 
      - ./src:/app
    depends_on:
      - db
    tty: true
    stdin_open: true

  web:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./src:/app
