version: '3'

services:
  web:
    build: ./web
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
  db:
    image: postgres:13.3
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
