version: '3'
services:
  front:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    command: /bin/sh -c 'cd react_app && yarn start'
    ports:
      - '3000:3000'
