version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
  front:
    build: 
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/app
    command: /bin/sh -c "cd react_app && yarn start"
    ports:
      - '3000:3000'
